services:
  web:
    build:
      context: .
    env_file:
      - .env
    command: gunicorn -b=0.0.0.0:8000 blogioma.wsgi:application
    volumes:
      - static_volume:/home/blogioma/static
      - media_volume:/home/blogioma/media
    ports:
      - 8000:8000

  redis:
    image: redis:latest
    command: redis-server --bind redis --maxmemory 256mb
    expose:
      - 6379
    depends_on:
      - web

  celery:
    build: 
      context: .
    env_file:
      - .env
    command: celery -A blogioma worker -l INFO -P gevent
    depends_on:
      - web
      - redis

  nginx:
    build:
      context: ./nginx
    volumes:
      - static_volume:/home/blogioma/static
      - media_volume:/home/blogioma/media
    ports:
      - 80:80
    depends_on:
      - web

volumes:
  static_volume:
  media_volume:
