# Generated by Django 4.2.3 on 2024-04-25 17:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0002_alter_report_article'),
    ]

    operations = [
        migrations.RenameField(
            model_name='report',
            old_name='article',
            new_name='reported_article',
        ),
    ]
