# Generated by Django 4.2.1 on 2023-06-28 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='viewings',
            field=models.IntegerField(default=0, verbose_name='Просмотры'),
        ),
        migrations.AlterField(
            model_name='article',
            name='headling',
            field=models.CharField(max_length=32, verbose_name='Заголовок'),
        ),
    ]
