# Generated by Django 4.2.1 on 2023-06-28 11:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_article_viewings_alter_article_headling'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='password',
        ),
    ]
