# Generated by Django 4.2.3 on 2023-07-16 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_comment'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'verbose_name': 'Комментарий', 'verbose_name_plural': 'Комментарии'},
        ),
        migrations.AddField(
            model_name='article',
            name='reports',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Репорты'),
        ),
    ]
