# Generated by Django 4.2.3 on 2023-08-22 14:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_comment_update_alter_comment_pub_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.CharField(choices=[('Запрещённая реклама', 'Запрещённая реклама (казино, порно-сайты и т.п.)'), ('Запрещённый контент', 'Контент, который неприятен некоторым читателям (шок-контент и т.п.), запрещённый законом или трагичный контент'), ('18+ контент', '18+ контент'), ('Обман/мошенничество', 'Обман/мошенничество'), ('Враждебные или оскорбительные высказывания', 'Враждебные или оскорбительные высказывания'), ('Нарушение авторского права', 'Нарушение авторского права'), ('Слив данных/медиа', 'Опубликование секретных данных (платные курсы, откровенные фото и т.п.)')], max_length=110, verbose_name='Причина')),
                ('desc', models.CharField(blank=True, max_length=200, null=True, verbose_name='Описание')),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.article')),
            ],
            options={
                'verbose_name': 'Жалоба',
                'verbose_name_plural': 'Жалобы',
            },
        ),
    ]
