# Generated by Django 4.2.3 on 2023-08-28 09:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_report'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='article',
            options={'verbose_name': 'Article', 'verbose_name_plural': 'Articles'},
        ),
        migrations.AlterModelOptions(
            name='comment',
            options={'verbose_name': 'Comment', 'verbose_name_plural': 'Comments'},
        ),
        migrations.AlterModelOptions(
            name='profile',
            options={'verbose_name': 'Profile', 'verbose_name_plural': 'Profiles'},
        ),
        migrations.AlterModelOptions(
            name='report',
            options={'verbose_name': 'Report', 'verbose_name_plural': 'Reports'},
        ),
        migrations.AlterField(
            model_name='article',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.profile', verbose_name='Author'),
        ),
        migrations.AlterField(
            model_name='article',
            name='full_text',
            field=models.TextField(verbose_name='Text'),
        ),
        migrations.AlterField(
            model_name='article',
            name='headling',
            field=models.CharField(max_length=32, verbose_name='Headling'),
        ),
        migrations.AlterField(
            model_name='article',
            name='pub_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Date of publication'),
        ),
        migrations.AlterField(
            model_name='article',
            name='reports',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Reports'),
        ),
        migrations.AlterField(
            model_name='article',
            name='update',
            field=models.DateTimeField(default=None, null=True, verbose_name='Date of update'),
        ),
        migrations.AlterField(
            model_name='article',
            name='viewings',
            field=models.IntegerField(default=0, verbose_name='Viewings'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='pub_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Date of send'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='text',
            field=models.CharField(max_length=400, verbose_name='Comment text'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='update',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Date of update'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='last_login',
            field=models.DateTimeField(auto_now=True, verbose_name='Last login'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='pfp',
            field=models.ImageField(blank=True, upload_to='get_username/', verbose_name='Profile picture'),
        ),
        migrations.AlterField(
            model_name='report',
            name='desc',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='report',
            name='reason',
            field=models.CharField(choices=[('Banned advertising', 'Banned advertising (casino, porn-sites, etc.)'), ('Banned content', 'Content that is unpleasant to some readers (shock content, etc.), illegal or tragic content'), ('18+ content', '18+ content'), ('Scam', 'Scam'), ('Swearing', 'Swearing'), ('Copyright infringement', 'Copyright infringement'), ('Data/media leakage', 'Data/media leakage (paid courses, candid photos, etc.)')], max_length=110, verbose_name='Reason'),
        ),
    ]
