# Generated by Django 4.2.3 on 2024-04-23 15:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('headling', models.CharField(max_length=32, verbose_name='Headling')),
                ('full_text', models.TextField(verbose_name='Text')),
                ('pub_date', models.DateTimeField(auto_now_add=True, verbose_name='Date of publication')),
                ('viewings', models.IntegerField(default=0, verbose_name='Viewings')),
                ('update', models.DateTimeField(default=None, null=True, verbose_name='Date of update')),
                ('reports', models.IntegerField(blank=True, default=0, null=True, verbose_name='Reports')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authentication.user', verbose_name='Author')),
            ],
            options={
                'verbose_name': 'Article',
                'verbose_name_plural': 'Articles',
            },
        ),
    ]
