# Generated by Django 4.2.3 on 2024-04-25 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0003_rename_article_report_reported_article'),
        ('articles', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='article',
            options={'ordering': ['pub_date'], 'verbose_name': 'Article', 'verbose_name_plural': 'Articles'},
        ),
        migrations.RemoveField(
            model_name='article',
            name='reports',
        ),
        migrations.AddField(
            model_name='article',
            name='reports',
            field=models.ManyToManyField(blank=True, null=True, to='feedback.report'),
        ),
    ]
