# Generated by Django 4.2.11 on 2024-06-04 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0003_alter_article_reports'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='headling',
            field=models.CharField(max_length=100, verbose_name='Headling'),
        ),
    ]
