# Generated by Django 4.2.16 on 2024-12-04 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0005_alter_article_author'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='headling',
        ),
        migrations.AddField(
            model_name='article',
            name='heading',
            field=models.CharField(default='default_heading', max_length=100, verbose_name='Heading'),
            preserve_default=False,
        ),
    ]
