# Generated by Django 4.2.11 on 2024-06-05 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='linkedin',
            field=models.CharField(max_length=2048, null=True, verbose_name='LinkedIn link'),
        ),
        migrations.AddField(
            model_name='profile',
            name='tiktok',
            field=models.CharField(max_length=2048, null=True, verbose_name='TikTok link'),
        ),
        migrations.AddField(
            model_name='profile',
            name='twitch',
            field=models.CharField(max_length=2048, null=True, verbose_name='Twitch link'),
        ),
        migrations.AddField(
            model_name='profile',
            name='youtube',
            field=models.CharField(max_length=2048, null=True, verbose_name='Youtube link'),
        ),
    ]
