# Generated by Django 4.2.11 on 2024-06-07 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_profile_linkedin_profile_tiktok_profile_twitch_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='linkedin',
            field=models.CharField(blank=True, max_length=2048, null=True, verbose_name='LinkedIn link'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='tiktok',
            field=models.CharField(blank=True, max_length=2048, null=True, verbose_name='TikTok link'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='twitch',
            field=models.CharField(blank=True, max_length=2048, null=True, verbose_name='Twitch link'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='youtube',
            field=models.CharField(blank=True, max_length=2048, null=True, verbose_name='Youtube link'),
        ),
    ]
