/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './app/routes/__root'
import { Route as FeedbackImport } from './app/routes/feedback'
import { Route as ArticlesImport } from './app/routes/articles'
import { Route as AboutImport } from './app/routes/about'
import { Route as IndexImport } from './app/routes/index'
import { Route as SearchIndexImport } from './app/routes/search/index'
import { Route as SearchQueryImport } from './app/routes/search/$query'
import { Route as ProfileSettingsImport } from './app/routes/profile/settings'
import { Route as AuthSignupImport } from './app/routes/auth/sign_up'
import { Route as AuthLoginImport } from './app/routes/auth/log_in'
import { Route as ArticleUpdateImport } from './app/routes/article/update'
import { Route as ArticleRandomImport } from './app/routes/article/random'
import { Route as ArticleDeleteImport } from './app/routes/article/delete'
import { Route as ArticleAddImport } from './app/routes/article/add'
import { Route as ProfileUsernameIndexImport } from './app/routes/profile/$username/index'
import { Route as ArticlePkIndexImport } from './app/routes/article/$pk/index'
import { Route as ArticlePkReportImport } from './app/routes/article/$pk/report'
import { Route as ArticlePkCommentsIndexImport } from './app/routes/article/$pk/comments/index'
import { Route as ArticlePkCommentsUpdateImport } from './app/routes/article/$pk/comments/update'
import { Route as ArticlePkCommentsDeleteImport } from './app/routes/article/$pk/comments/delete'
import { Route as ArticlePkCommentsAddImport } from './app/routes/article/$pk/comments/add'

// Create/Update Routes

const FeedbackRoute = FeedbackImport.update({
  id: '/feedback',
  path: '/feedback',
  getParentRoute: () => rootRoute,
} as any)

const ArticlesRoute = ArticlesImport.update({
  id: '/articles',
  path: '/articles',
  getParentRoute: () => rootRoute,
} as any)

const AboutRoute = AboutImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const SearchIndexRoute = SearchIndexImport.update({
  id: '/search/',
  path: '/search/',
  getParentRoute: () => rootRoute,
} as any)

const SearchQueryRoute = SearchQueryImport.update({
  id: '/search/$query',
  path: '/search/$query',
  getParentRoute: () => rootRoute,
} as any)

const ProfileSettingsRoute = ProfileSettingsImport.update({
  id: '/profile/settings',
  path: '/profile/settings',
  getParentRoute: () => rootRoute,
} as any)

const AuthSignupRoute = AuthSignupImport.update({
  id: '/auth/sign_up',
  path: '/auth/sign_up',
  getParentRoute: () => rootRoute,
} as any)

const AuthLoginRoute = AuthLoginImport.update({
  id: '/auth/log_in',
  path: '/auth/log_in',
  getParentRoute: () => rootRoute,
} as any)

const ArticleUpdateRoute = ArticleUpdateImport.update({
  id: '/article/update',
  path: '/article/update',
  getParentRoute: () => rootRoute,
} as any)

const ArticleRandomRoute = ArticleRandomImport.update({
  id: '/article/random',
  path: '/article/random',
  getParentRoute: () => rootRoute,
} as any)

const ArticleDeleteRoute = ArticleDeleteImport.update({
  id: '/article/delete',
  path: '/article/delete',
  getParentRoute: () => rootRoute,
} as any)

const ArticleAddRoute = ArticleAddImport.update({
  id: '/article/add',
  path: '/article/add',
  getParentRoute: () => rootRoute,
} as any)

const ProfileUsernameIndexRoute = ProfileUsernameIndexImport.update({
  id: '/profile/$username/',
  path: '/profile/$username/',
  getParentRoute: () => rootRoute,
} as any)

const ArticlePkIndexRoute = ArticlePkIndexImport.update({
  id: '/article/$pk/',
  path: '/article/$pk/',
  getParentRoute: () => rootRoute,
} as any)

const ArticlePkReportRoute = ArticlePkReportImport.update({
  id: '/article/$pk/report',
  path: '/article/$pk/report',
  getParentRoute: () => rootRoute,
} as any)

const ArticlePkCommentsIndexRoute = ArticlePkCommentsIndexImport.update({
  id: '/article/$pk/comments/',
  path: '/article/$pk/comments/',
  getParentRoute: () => rootRoute,
} as any)

const ArticlePkCommentsUpdateRoute = ArticlePkCommentsUpdateImport.update({
  id: '/article/$pk/comments/update',
  path: '/article/$pk/comments/update',
  getParentRoute: () => rootRoute,
} as any)

const ArticlePkCommentsDeleteRoute = ArticlePkCommentsDeleteImport.update({
  id: '/article/$pk/comments/delete',
  path: '/article/$pk/comments/delete',
  getParentRoute: () => rootRoute,
} as any)

const ArticlePkCommentsAddRoute = ArticlePkCommentsAddImport.update({
  id: '/article/$pk/comments/add',
  path: '/article/$pk/comments/add',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutImport
      parentRoute: typeof rootRoute
    }
    '/articles': {
      id: '/articles'
      path: '/articles'
      fullPath: '/articles'
      preLoaderRoute: typeof ArticlesImport
      parentRoute: typeof rootRoute
    }
    '/feedback': {
      id: '/feedback'
      path: '/feedback'
      fullPath: '/feedback'
      preLoaderRoute: typeof FeedbackImport
      parentRoute: typeof rootRoute
    }
    '/article/add': {
      id: '/article/add'
      path: '/article/add'
      fullPath: '/article/add'
      preLoaderRoute: typeof ArticleAddImport
      parentRoute: typeof rootRoute
    }
    '/article/delete': {
      id: '/article/delete'
      path: '/article/delete'
      fullPath: '/article/delete'
      preLoaderRoute: typeof ArticleDeleteImport
      parentRoute: typeof rootRoute
    }
    '/article/random': {
      id: '/article/random'
      path: '/article/random'
      fullPath: '/article/random'
      preLoaderRoute: typeof ArticleRandomImport
      parentRoute: typeof rootRoute
    }
    '/article/update': {
      id: '/article/update'
      path: '/article/update'
      fullPath: '/article/update'
      preLoaderRoute: typeof ArticleUpdateImport
      parentRoute: typeof rootRoute
    }
    '/auth/log_in': {
      id: '/auth/log_in'
      path: '/auth/log_in'
      fullPath: '/auth/log_in'
      preLoaderRoute: typeof AuthLoginImport
      parentRoute: typeof rootRoute
    }
    '/auth/sign_up': {
      id: '/auth/sign_up'
      path: '/auth/sign_up'
      fullPath: '/auth/sign_up'
      preLoaderRoute: typeof AuthSignupImport
      parentRoute: typeof rootRoute
    }
    '/profile/settings': {
      id: '/profile/settings'
      path: '/profile/settings'
      fullPath: '/profile/settings'
      preLoaderRoute: typeof ProfileSettingsImport
      parentRoute: typeof rootRoute
    }
    '/search/$query': {
      id: '/search/$query'
      path: '/search/$query'
      fullPath: '/search/$query'
      preLoaderRoute: typeof SearchQueryImport
      parentRoute: typeof rootRoute
    }
    '/search/': {
      id: '/search/'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof SearchIndexImport
      parentRoute: typeof rootRoute
    }
    '/article/$pk/report': {
      id: '/article/$pk/report'
      path: '/article/$pk/report'
      fullPath: '/article/$pk/report'
      preLoaderRoute: typeof ArticlePkReportImport
      parentRoute: typeof rootRoute
    }
    '/article/$pk/': {
      id: '/article/$pk/'
      path: '/article/$pk'
      fullPath: '/article/$pk'
      preLoaderRoute: typeof ArticlePkIndexImport
      parentRoute: typeof rootRoute
    }
    '/profile/$username/': {
      id: '/profile/$username/'
      path: '/profile/$username'
      fullPath: '/profile/$username'
      preLoaderRoute: typeof ProfileUsernameIndexImport
      parentRoute: typeof rootRoute
    }
    '/article/$pk/comments/add': {
      id: '/article/$pk/comments/add'
      path: '/article/$pk/comments/add'
      fullPath: '/article/$pk/comments/add'
      preLoaderRoute: typeof ArticlePkCommentsAddImport
      parentRoute: typeof rootRoute
    }
    '/article/$pk/comments/delete': {
      id: '/article/$pk/comments/delete'
      path: '/article/$pk/comments/delete'
      fullPath: '/article/$pk/comments/delete'
      preLoaderRoute: typeof ArticlePkCommentsDeleteImport
      parentRoute: typeof rootRoute
    }
    '/article/$pk/comments/update': {
      id: '/article/$pk/comments/update'
      path: '/article/$pk/comments/update'
      fullPath: '/article/$pk/comments/update'
      preLoaderRoute: typeof ArticlePkCommentsUpdateImport
      parentRoute: typeof rootRoute
    }
    '/article/$pk/comments/': {
      id: '/article/$pk/comments/'
      path: '/article/$pk/comments'
      fullPath: '/article/$pk/comments'
      preLoaderRoute: typeof ArticlePkCommentsIndexImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/articles': typeof ArticlesRoute
  '/feedback': typeof FeedbackRoute
  '/article/add': typeof ArticleAddRoute
  '/article/delete': typeof ArticleDeleteRoute
  '/article/random': typeof ArticleRandomRoute
  '/article/update': typeof ArticleUpdateRoute
  '/auth/log_in': typeof AuthLoginRoute
  '/auth/sign_up': typeof AuthSignupRoute
  '/profile/settings': typeof ProfileSettingsRoute
  '/search/$query': typeof SearchQueryRoute
  '/search': typeof SearchIndexRoute
  '/article/$pk/report': typeof ArticlePkReportRoute
  '/article/$pk': typeof ArticlePkIndexRoute
  '/profile/$username': typeof ProfileUsernameIndexRoute
  '/article/$pk/comments/add': typeof ArticlePkCommentsAddRoute
  '/article/$pk/comments/delete': typeof ArticlePkCommentsDeleteRoute
  '/article/$pk/comments/update': typeof ArticlePkCommentsUpdateRoute
  '/article/$pk/comments': typeof ArticlePkCommentsIndexRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/articles': typeof ArticlesRoute
  '/feedback': typeof FeedbackRoute
  '/article/add': typeof ArticleAddRoute
  '/article/delete': typeof ArticleDeleteRoute
  '/article/random': typeof ArticleRandomRoute
  '/article/update': typeof ArticleUpdateRoute
  '/auth/log_in': typeof AuthLoginRoute
  '/auth/sign_up': typeof AuthSignupRoute
  '/profile/settings': typeof ProfileSettingsRoute
  '/search/$query': typeof SearchQueryRoute
  '/search': typeof SearchIndexRoute
  '/article/$pk/report': typeof ArticlePkReportRoute
  '/article/$pk': typeof ArticlePkIndexRoute
  '/profile/$username': typeof ProfileUsernameIndexRoute
  '/article/$pk/comments/add': typeof ArticlePkCommentsAddRoute
  '/article/$pk/comments/delete': typeof ArticlePkCommentsDeleteRoute
  '/article/$pk/comments/update': typeof ArticlePkCommentsUpdateRoute
  '/article/$pk/comments': typeof ArticlePkCommentsIndexRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/articles': typeof ArticlesRoute
  '/feedback': typeof FeedbackRoute
  '/article/add': typeof ArticleAddRoute
  '/article/delete': typeof ArticleDeleteRoute
  '/article/random': typeof ArticleRandomRoute
  '/article/update': typeof ArticleUpdateRoute
  '/auth/log_in': typeof AuthLoginRoute
  '/auth/sign_up': typeof AuthSignupRoute
  '/profile/settings': typeof ProfileSettingsRoute
  '/search/$query': typeof SearchQueryRoute
  '/search/': typeof SearchIndexRoute
  '/article/$pk/report': typeof ArticlePkReportRoute
  '/article/$pk/': typeof ArticlePkIndexRoute
  '/profile/$username/': typeof ProfileUsernameIndexRoute
  '/article/$pk/comments/add': typeof ArticlePkCommentsAddRoute
  '/article/$pk/comments/delete': typeof ArticlePkCommentsDeleteRoute
  '/article/$pk/comments/update': typeof ArticlePkCommentsUpdateRoute
  '/article/$pk/comments/': typeof ArticlePkCommentsIndexRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/articles'
    | '/feedback'
    | '/article/add'
    | '/article/delete'
    | '/article/random'
    | '/article/update'
    | '/auth/log_in'
    | '/auth/sign_up'
    | '/profile/settings'
    | '/search/$query'
    | '/search'
    | '/article/$pk/report'
    | '/article/$pk'
    | '/profile/$username'
    | '/article/$pk/comments/add'
    | '/article/$pk/comments/delete'
    | '/article/$pk/comments/update'
    | '/article/$pk/comments'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/articles'
    | '/feedback'
    | '/article/add'
    | '/article/delete'
    | '/article/random'
    | '/article/update'
    | '/auth/log_in'
    | '/auth/sign_up'
    | '/profile/settings'
    | '/search/$query'
    | '/search'
    | '/article/$pk/report'
    | '/article/$pk'
    | '/profile/$username'
    | '/article/$pk/comments/add'
    | '/article/$pk/comments/delete'
    | '/article/$pk/comments/update'
    | '/article/$pk/comments'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/articles'
    | '/feedback'
    | '/article/add'
    | '/article/delete'
    | '/article/random'
    | '/article/update'
    | '/auth/log_in'
    | '/auth/sign_up'
    | '/profile/settings'
    | '/search/$query'
    | '/search/'
    | '/article/$pk/report'
    | '/article/$pk/'
    | '/profile/$username/'
    | '/article/$pk/comments/add'
    | '/article/$pk/comments/delete'
    | '/article/$pk/comments/update'
    | '/article/$pk/comments/'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  ArticlesRoute: typeof ArticlesRoute
  FeedbackRoute: typeof FeedbackRoute
  ArticleAddRoute: typeof ArticleAddRoute
  ArticleDeleteRoute: typeof ArticleDeleteRoute
  ArticleRandomRoute: typeof ArticleRandomRoute
  ArticleUpdateRoute: typeof ArticleUpdateRoute
  AuthLoginRoute: typeof AuthLoginRoute
  AuthSignupRoute: typeof AuthSignupRoute
  ProfileSettingsRoute: typeof ProfileSettingsRoute
  SearchQueryRoute: typeof SearchQueryRoute
  SearchIndexRoute: typeof SearchIndexRoute
  ArticlePkReportRoute: typeof ArticlePkReportRoute
  ArticlePkIndexRoute: typeof ArticlePkIndexRoute
  ProfileUsernameIndexRoute: typeof ProfileUsernameIndexRoute
  ArticlePkCommentsAddRoute: typeof ArticlePkCommentsAddRoute
  ArticlePkCommentsDeleteRoute: typeof ArticlePkCommentsDeleteRoute
  ArticlePkCommentsUpdateRoute: typeof ArticlePkCommentsUpdateRoute
  ArticlePkCommentsIndexRoute: typeof ArticlePkCommentsIndexRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  ArticlesRoute: ArticlesRoute,
  FeedbackRoute: FeedbackRoute,
  ArticleAddRoute: ArticleAddRoute,
  ArticleDeleteRoute: ArticleDeleteRoute,
  ArticleRandomRoute: ArticleRandomRoute,
  ArticleUpdateRoute: ArticleUpdateRoute,
  AuthLoginRoute: AuthLoginRoute,
  AuthSignupRoute: AuthSignupRoute,
  ProfileSettingsRoute: ProfileSettingsRoute,
  SearchQueryRoute: SearchQueryRoute,
  SearchIndexRoute: SearchIndexRoute,
  ArticlePkReportRoute: ArticlePkReportRoute,
  ArticlePkIndexRoute: ArticlePkIndexRoute,
  ProfileUsernameIndexRoute: ProfileUsernameIndexRoute,
  ArticlePkCommentsAddRoute: ArticlePkCommentsAddRoute,
  ArticlePkCommentsDeleteRoute: ArticlePkCommentsDeleteRoute,
  ArticlePkCommentsUpdateRoute: ArticlePkCommentsUpdateRoute,
  ArticlePkCommentsIndexRoute: ArticlePkCommentsIndexRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/about",
        "/articles",
        "/feedback",
        "/article/add",
        "/article/delete",
        "/article/random",
        "/article/update",
        "/auth/log_in",
        "/auth/sign_up",
        "/profile/settings",
        "/search/$query",
        "/search/",
        "/article/$pk/report",
        "/article/$pk/",
        "/profile/$username/",
        "/article/$pk/comments/add",
        "/article/$pk/comments/delete",
        "/article/$pk/comments/update",
        "/article/$pk/comments/"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/about": {
      "filePath": "about.tsx"
    },
    "/articles": {
      "filePath": "articles.tsx"
    },
    "/feedback": {
      "filePath": "feedback.tsx"
    },
    "/article/add": {
      "filePath": "article/add.tsx"
    },
    "/article/delete": {
      "filePath": "article/delete.tsx"
    },
    "/article/random": {
      "filePath": "article/random.tsx"
    },
    "/article/update": {
      "filePath": "article/update.tsx"
    },
    "/auth/log_in": {
      "filePath": "auth/log_in.tsx"
    },
    "/auth/sign_up": {
      "filePath": "auth/sign_up.tsx"
    },
    "/profile/settings": {
      "filePath": "profile/settings.tsx"
    },
    "/search/$query": {
      "filePath": "search/$query.tsx"
    },
    "/search/": {
      "filePath": "search/index.tsx"
    },
    "/article/$pk/report": {
      "filePath": "article/$pk/report.tsx"
    },
    "/article/$pk/": {
      "filePath": "article/$pk/index.tsx"
    },
    "/profile/$username/": {
      "filePath": "profile/$username/index.tsx"
    },
    "/article/$pk/comments/add": {
      "filePath": "article/$pk/comments/add.tsx"
    },
    "/article/$pk/comments/delete": {
      "filePath": "article/$pk/comments/delete.tsx"
    },
    "/article/$pk/comments/update": {
      "filePath": "article/$pk/comments/update.tsx"
    },
    "/article/$pk/comments/": {
      "filePath": "article/$pk/comments/index.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
